/**
 * Code definitions and metadata for synchronized line highlighting.
 */

export const PSEUDOCODE_LINES = [
  { id: 1, text: "1. Sort items by decreasing profit/weight ratio (P[i] / W[i])." },
  { id: 2, text: "2. Create root node: level = -1, weight = 0, profit = 0." },
  { id: 3, text: "3. Calculate root upper bound using fractional relaxation." },
  { id: 4, text: "4. Insert root node into FIFO queue." },
  { id: 5, text: "5. Initialize maxProfit = 0." },
  { id: 6, text: "6. While FIFO queue is not empty:" },
  { id: 7, text: "7.     Node u = queue.remove()  // Dequeue from FRONT (FIFO)" },
  { id: 8, text: "8.     If u.level == n - 1: continue  // All items examined" },
  { id: 9, text: "9.     Create INCLUDE child: Take items[nextLevel]" },
  { id: 10, text: "10.    If include.weight <= capacity:" },
  { id: 11, text: "11.        If include.profit > maxProfit: maxProfit = include.profit" },
  { id: 12, text: "12.        include.bound = calculateBound(include)" },
  { id: 13, text: "13.        If include.bound > maxProfit: queue.add(include)  // KEEP" },
  { id: 14, text: "14.        Else: Prune include node (Bound <= maxProfit)" },
  { id: 15, text: "15.    Else: Prune include node (Weight > Capacity)" },
  { id: 16, text: "16.    Create EXCLUDE child: Skip items[nextLevel]" },
  { id: 17, text: "17.    exclude.bound = calculateBound(exclude)" },
  { id: 18, text: "18.    If exclude.bound > maxProfit: queue.add(exclude)  // KEEP" },
  { id: 19, text: "19.    Else: Prune exclude node (Bound <= maxProfit)" },
  { id: 20, text: "20. Return maxProfit and optimal solution" }
];

export const JAVA_CODE_LINES = [
  { id: 1, text: "import java.util.*;" },
  { id: 2, text: "" },
  { id: 3, text: "class Item {" },
  { id: 4, text: "    int weight, profit;" },
  { id: 5, text: "    double ratio;" },
  { id: 6, text: "    Item(int weight, int profit) {" },
  { id: 7, text: "        this.weight = weight;" },
  { id: 8, text: "        this.profit = profit;" },
  { id: 9, text: "        this.ratio = (double) profit / weight;" },
  { id: 10, text: "    }" },
  { id: 11, text: "}" },
  { id: 12, text: "" },
  { id: 13, text: "class Node {" },
  { id: 14, text: "    int level, weight, profit;" },
  { id: 15, text: "    double bound;" },
  { id: 16, text: "    Node(int level, int weight, int profit, double bound) {" },
  { id: 17, text: "        this.level = level; this.weight = weight;" },
  { id: 18, text: "        this.profit = profit; this.bound = bound;" },
  { id: 19, text: "    }" },
  { id: 20, text: "}" },
  { id: 21, text: "" },
  { id: 22, text: "public class FIFOKnapsack {" },
  { id: 23, text: "    static int capacity;" },
  { id: 24, text: "    static Item[] items;" },
  { id: 25, text: "" },
  { id: 26, text: "    static double calculateBound(Node u) {" },
  { id: 27, text: "        if (u.weight >= capacity) return 0;" },
  { id: 28, text: "        double profitBound = u.profit;" },
  { id: 29, text: "        int totalWeight = u.weight;" },
  { id: 30, text: "        int j = u.level + 1;" },
  { id: 31, text: "        while (j < items.length &&" },
  { id: 32, text: "               totalWeight + items[j].weight <= capacity) {" },
  { id: 33, text: "            totalWeight += items[j].weight;" },
  { id: 34, text: "            profitBound += items[j].profit;" },
  { id: 35, text: "            j++;" },
  { id: 36, text: "        }" },
  { id: 37, text: "        if (j < items.length) {" },
  { id: 38, text: "            int remaining = capacity - totalWeight;" },
  { id: 39, text: "            profitBound += remaining * items[j].ratio;" },
  { id: 40, text: "        }" },
  { id: 41, text: "        return profitBound;" },
  { id: 42, text: "    }" },
  { id: 43, text: "" },
  { id: 44, text: "    static int knapsack() {" },
  { id: 45, text: "        Queue<Node> queue = new LinkedList<>();" },
  { id: 46, text: "        Node root = new Node(-1, 0, 0, 0);" },
  { id: 47, text: "        root.bound = calculateBound(root);" },
  { id: 48, text: "        queue.add(root);" },
  { id: 49, text: "        int maxProfit = 0;" },
  { id: 50, text: "" },
  { id: 51, text: "        while (!queue.isEmpty()) {" },
  { id: 52, text: "            Node u = queue.remove();" },
  { id: 53, text: "            if (u.level == items.length - 1) continue;" },
  { id: 54, text: "            int nextLevel = u.level + 1;" },
  { id: 55, text: "" },
  { id: 56, text: "            Node include = new Node(" },
  { id: 57, text: "                nextLevel," },
  { id: 58, text: "                u.weight + items[nextLevel].weight," },
  { id: 59, text: "                u.profit + items[nextLevel].profit," },
  { id: 60, text: "                0);" },
  { id: 61, text: "" },
  { id: 62, text: "            if (include.weight <= capacity) {" },
  { id: 63, text: "                if (include.profit > maxProfit)" },
  { id: 64, text: "                    maxProfit = include.profit;" },
  { id: 65, text: "                include.bound = calculateBound(include);" },
  { id: 66, text: "                if (include.bound > maxProfit)" },
  { id: 67, text: "                    queue.add(include);" },
  { id: 68, text: "            }" },
  { id: 69, text: "" },
  { id: 70, text: "            Node exclude = new Node(" },
  { id: 71, text: "                nextLevel," },
  { id: 72, text: "                u.weight," },
  { id: 73, text: "                u.profit," },
  { id: 74, text: "                0);" },
  { id: 75, text: "            exclude.bound = calculateBound(exclude);" },
  { id: 76, text: "            if (exclude.bound > maxProfit)" },
  { id: 77, text: "                queue.add(exclude);" },
  { id: 78, text: "        }" },
  { id: 79, text: "        return maxProfit;" },
  { id: 80, text: "    }" },
  { id: 81, text: "" },
  { id: 82, text: "    public static void main(String[] args) {" },
  { id: 83, text: "        Arrays.sort(items, (a, b) ->" },
  { id: 84, text: "            Double.compare(b.ratio, a.ratio)" },
  { id: 85, text: "        );" },
  { id: 86, text: "        int result = knapsack();" },
  { id: 87, text: "        System.out.println(\"Maximum Profit = \" + result);" },
  { id: 88, text: "    }" },
  { id: 89, text: "}" }
];
